[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { version = "0.3.1", features = ["register-docs"] }
gdrust_kit = { path = "../../gdrust_kit", version = "0.1.2", features = ["dev"]}
