[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
godot = { version = "0.2.4" }
gdrust_kit = { path = "../../gdrust_kit", version = "0.1.0", features = ["dev"]}
