name: CD Pipeline

on:
  push:
    tags:
      - "v*"

jobs:
  create-release:
    name: Create Github Release
    permissions:
      contents: write
    if: contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download Builds
        uses: actions/download-artifact@v4
        with:
          name: games
          path: build/

      - name: Create Release Directory
        run: mkdir -v -p release

      - name: Zip Linux Artifacts
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release/linux.zip build/linux

      - name: Zip Windows Artifacts
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release/windows.zip build/windows

      - name: Zip Mac Artifacts
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r release/mac.zip build/mac

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          make_latest: true
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true
          files: |
            release/*


  deploy-itchio:
    name: Deploy to itch.io
    if: contains(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform:
          - name: Windows
            channel: windows

          - name: MacOs
            channel: mac

          - name: Linux
            channel: linux

    steps:
      - name: Download Builds
        uses: actions/download-artifact@v4
        with:
          name: games
          path: build/

      - name: Deploy ${{ matrix.platform.name }}
        uses: manleydev/butler-publish-itchio-action@v1.0.3
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
          CHANNEL: ${{ matrix.platform.channel }}
          ITCH_GAME: ${{ vars.ITCHIO_GAMENAME }}
          ITCH_USER: ${{ secrets.ITCHIO_USERNAME }}
          PACKAGE: build/${{ matrix.platform.channel }}
          VERSION: ${{ github.ref_name }}

  discord-notify-itchio:
    name: Notify Discord Itch.io
    needs: deploy-itchio
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        uses: stegzilla/discord-notify@v4
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          ITCHIO_SECRET_URL: ${{ secrets.ITCHIO_SECRET_URL }}
        if: ${{ env.DISCORD_WEBHOOK != '' && env.ITCHIO_SECRET_URL != '' }}
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          title: Neue Version veröffentlicht
          message: "Spiel: **${{ vars.ITCHIO_GAMENAME }}**\nVersion: ${{ github.ref_name }}\nLink zur zur Itch.io Seite: ${{ secrets.ITCHIO_SECRET_URL }}"
          avatar_url: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
          username: My Purpose Is To Notify
