name: CD

on:
  release:
    types: [published]

env:
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

jobs:
  itchio-windows:
    name: Itch.io Windows Deploy
    runs-on: ubuntu-latest
    container:
      image: robotnikdev/godot-rust-ci:4.3
      credentials:
        username: robotnikdev
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p build/windows
          mkdir -v -p build/linux
          mkdir -v -p build/web
      - name: release-downloader
        uses: robinraju/release-downloader@v1
        with:
          latest: true
          token: ${{ secrets.GH_PAT }}
          fileName: '*.zip'
          out-file-path: 'build/windows'
          extract: true
      - name: Deploy
        run: |
          butler push build/windows ${{ secrets.ITCHIO_USERNAME }}/${{ vars.GAMENAME }}:windows --userversion ${{ github.ref }}

  itchio-linux:
    name: Itch.io Linux Deploy
    runs-on: ubuntu-latest
    container:
      image: robotnikdev/godot-rust-ci:4.3
      credentials:
        username: robotnikdev
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          path: build/linux
      - name: Deploy
        run: |
          butler push ./build/linux ${{ secrets.ITCHIO_USERNAME }}/${{ secrets.ITCHIO_GAMENAME }}:linux --userversion ${{ github.ref }}

  itchio-web:
    name: Itch.io Web Deploy
    runs-on: ubuntu-latest
    container:
      image: robotnikdev/godot-rust-ci:4.3
      credentials:
        username: robotnikdev
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: web
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          path: build/web
      - name: Deploy
        run: |
          butler push ./build/web ${{ secrets.ITCHIO_USERNAME }}/${{ secrets.ITCHIO_GAMENAME }}:web --userversion ${{ github.ref }}
