name: CI Test

on: push

env:
  RUST_PROJECT_PATH: rust

jobs:
  linux-test-rust:
    name: Linux Test Rust
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup Rust
        run: rustup default stable
      - name: Test Rust
        run: |
          cd $RUST_PROJECT_PATH
          cargo test --no-fail-fast --release -v -v

  windows-test-rust:
    name: Windows Test Rust
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup Rust
        run: |
          rustup target add x86_64-pc-windows-gnu
          sudo apt install mingw-w64
      - name: Test Rust
        run: |
          cd $RUST_PROJECT_PATH
          cargo test --target x86_64-pc-windows-gnu --no-fail-fast --release -v -v
